[package]
name = "gateawayapi"
version = "0.1.0"
edition = "2023"

[dependencies]
rocket = "0.5.0"
rocket-sync-db-pools = "0.4.0"
serde = { version = "1.0", features = ["derive"] }

[dependencies.rocket.sync]
default-features = false
version = "0.5.0"
features = ["json"]
