[package]

name = "api"

version = "0.1.0"

edition = "2023"

[dependencies]

rocket = "0.5.0-rc.1"

rocket_codegen = "0.5.0-rc.1"

rocket_contrib = "0.5.0-rc.1"

serde = "1.0.130"

serde_json = "1.0.66"

bcrypt = "0.10.0"

jsonwebtoken = "8.2.1"


